project:
  type: book

template-partials: 
  - title-block.html

book:
  title: "Studi Kelayakan dan Basic Desain Pembangunan Intake Mahakam"
  author: "Irpan Chumaedi"
  date: "Agustus 2024"
  chapters:
    - index.qmd
    - 1_pendahuluan.qmd
    - 2_tinjauan_pustaka.qmd
    - 3_gambaran_umum.qmd
    - 4_metodologi_penelitian.qmd
    - 5_analisa_pembahasan.qmd
    - 6_kesimpulan_saran.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    code-fold: true
    html-math-method: katex
    number-sections: true
    number-offset: 2
    number-depth: 3
  pdf:
    documentclass: scrreprt
    geometry: 
      - top=30 mm
      - left=30 mm
  docx: default

editor: visual
crossref:
  fig-title: '**Gambar**'
  tbl-title: '**Tabel**'
  #fig-labels: arabic
  title-delim: "**. **"
  fig-prefix: Gambar
  tbl-prefix: Tabel
